# Generated by Django 4.1.1 on 2022-10-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productkind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="kind",
        ),
    ]
