# Generated by Django 4.1.1 on 2022-10-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOrigin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(max_length=64)),
            ],
        ),
    ]
