# Generated by Django 4.1.1 on 2022-10-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_productorigin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="origin",
            field=models.ManyToManyField(
                related_name="products", to="products.productorigin"
            ),
        ),
    ]
