# Generated by Django 4.1.1 on 2022-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_product_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="origin",
            field=models.ManyToManyField(
                related_name="product", to="products.productorigin"
            ),
        ),
    ]
